# docker-compose.yml
version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/remedial_binar
      NODE_ENV: development
      PORT: 8889
      DB_HOST: host.docker.internal
    ports:
      - "8889:8889"
    command: bash -c "npm install -g sequelize-cli && npm run dev"
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: remedial_binar
      
